import { Art } from './models/art.model';
export const ARTS = [
  new Art('Christmas tree ornaments', 'Fused Glass', ['Bullseye Glass', 'Silver finding'], 7.00, ['https://github.com/KChellis/art-store-2/blob/master/src/assets/trees1.png', 'https://github.com/KChellis/art-store-2/blob/master/src/assets/trees2.png'],
  ['Regular Striped', 'Dot Striped', 'Dots'], 'Fused Glass Christmas Tree Ornaments in a variety of patterns. All pieces are handmade and no two pieces are exactly alike.', ['Bullseye', 'christmas', 'glass', 'xmas', 'fused', 'tree', 'handmade', 'ornaments'], 1),
  new Art('Dichroic Glass Necklaces and Earrings', 'Fused Glass', ['Dichroic glass', 'Silver Findings', 'Black Satin Cord'], 40.00, ['https://github.com/KChellis/art-store-2/blob/master/src/assets/necklaces.png', 'https://github.com/KChellis/art-store-2/blob/master/src/assets/labyrinth.png', 'https://github.com/KChellis/art-store-2/blob/master/src/assets/plummage.png', 'https://github.com/KChellis/art-store-2/blob/master/src/assets/circiut.png', 'https://github.com/KChellis/art-store-2/blob/master/src/assets/twostyle.png'], ['Plumage', 'Clockworks', 'Circuits', 'String Theory', 'Labyrinth'], 'Necklaces made with handcut dichroic glass. No two pieces are exactly alike', ['dichroic', 'necklace', 'glass', 'silver', 'fused', 'handmade'], 2),
  new Art('Sports Logo lampshade', 'Fused and Stained Glass', ['Bullseye glass', 'solder'], 200.00, ['https://github.com/KChellis/art-store-2/blob/master/src/assets/blazers.png', 'https://github.com/KChellis/art-store-2/blob/master/src/assets/blazers2.png', 'https://github.com/KChellis/art-store-2/blob/master/src/assets/colts.png'], ['Blazers', 'Colts', 'Packers', 'Other'], 'Custom lamp shades made with any design you desire. You choose the logo and background color you want. A more difficult logo may cost more. *Does not include lamp.', ['bullseye', 'lampshade', 'glass', 'silver', 'fused', 'handmade', 'sports', 'logo'], 3),
  new Art('Bmo glass window in frame', 'Stained and Fused Glass', ['stained glass', 'solder', 'wood frame'], 60.00, ['https://github.com/KChellis/art-store-2/blob/master/src/assets/bmo.png'], ['BMo'], 'A stained a fused glass depiction of BMo from Adventure Time', ['Bmo', 'adventure', 'glass', 'framed', 'fused', 'handmade'], 4),
  new Art('Dragonfly Suncatcher', 'Stained Glass', ['stained glass', 'solder'], 30.00, ['https://github.com/KChellis/art-store-2/blob/master/src/assets/dragonfly.png'], ['DragonFly'], 'This beautiful dragonfly suncatcher would look great in any window!', ['suncatcher', 'glass', 'dragonfly', 'handmade'], 5),
  new Art('Nintento ornaments', 'Fused Glass', ['Bullseye Glass', 'Silver finding'], 10.00, ['', ''],
  ['mushroom', 'triforce', 'heart container'], 'Fused Glass Nintendo Ornaments in a variety of patterns. All pieces are handmade and no two pieces are exactly alike.', ['Bullseye', 'christmas', 'glass', 'xmas', 'fused', 'nintendo', 'handmade', 'ornaments', 'video game', 'mushroom', 'heart', 'mario', 'zelda', 'triforce'], 6)


];
